spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_CLIENT_ID:null}
            client-secret: ${GIT_CLIENT_SECRET:null}
  profiles:
    active: security

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    
springdoc:
  swagger-ui:
    path: /
    url: /api-schema.yaml

logging:
  level:
    root: DEBUG
    com:
      freenow:
        clients:
          GithubOAuthClient: DEBUG

feign:
  client:
    config:
      github-oauth-token:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full