openapi: 3.0.3

info:
  title: Free Now Test task API
  version: 1.0.0
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.html
  contact:
    name: Andrei Alekseenko
    email: engelier@gmx.de

servers:
  - url: http://localhost:{port}/{base-path}
    description: Free NOW Service provider API
    variables:
      port:
        enum:
          - '8080'
        default: '8080'
      base-path:
        default: v1

tags:
  - name: Driver
  - name: Car

paths:

  /drivers:

    get:
      tags:
        - Driver
      operationId: findDrivers
      parameters:
        - name: status
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/OnlineStatus'
        - name: nextId
          in: query
          required: false
          description: Next Driver ID from whom to start ordered list
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: List of drivers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverList'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

  /driver:

    post:
      tags:
        - Driver
      operationId: createDriver
      requestBody:
        description: Create new Driver
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDriver'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

  /driver/{id}:

    get:
      tags:
        - Driver
      operationId: getDriver
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

    delete:
      tags:
        - Driver
      description: Delete existent Driver by ID
      operationId: deleteDriver
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        204:
          description: Driver deleted
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

    put:
      tags:
        - Driver
      operationId: updateLocation
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeoLocation'
      responses:
        202:
          description: Location updated successfully
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

  /driver/{id}/{carId}:

    put:
      tags:
        - Driver
      operationId: assignCar
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/carId'
      responses:
        202:
          description: Car added successfully
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        406:
          $ref: '#/components/responses/ValidationError'
        default:
          $ref: '#/components/responses/Unexpected'

    delete:
      tags:
        - Driver
      operationId: unassignCar
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        202:
          description: Car removed successfully
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

  /car:

    post:
      tags:
        - Car
      operationId: addCar
      requestBody:
        description: Add Car to fleet
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        201:
          description: Car inserted to fleet database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

  /car/{carId}:

    delete:
      tags:
        - Car
      description: Remove Car from fleet
      operationId: removeCar
      parameters:
        - $ref: '#/components/parameters/carId'
      responses:
        204:
          description: Car removed from fleet
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

    patch:
      tags:
        - Car
      description: Update Car parameter values
      operationId: modifyCar
      parameters:
        - $ref: '#/components/parameters/carId'
      requestBody:
        description: Modify Car
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCar'
      responses:
        202:
          description: Car information successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        400:
          $ref: '#/components/responses/ConstraintViolation'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

    get:
      tags:
        - Car
      description: Retrieve Car information
      operationId: carInfo
      parameters:
        - $ref: '#/components/parameters/carId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'

components:

  responses:

    Unexpected:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ConstraintViolation:
      description: Some constraints are violated.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Could not find entity with id.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ValidationError:
      description: Failed to validate business rules
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  parameters:

    id:
      name: id
      in: path
      required: true
      description: Driver ID
      schema:
        type: string
        format: uuid

    carId:
      name: carId
      in: path
      required: true
      description: Car ID
      schema:
        type: string
        format: uuid

  schemas:

    DriverList:
      title: List of selected drivers
      type: object
      required:
        - total
        - drivers
      properties:
        total:
          type: integer
          format: int32
        next:
          description: Next ID of a Driver not included into list
          type: string
          format: uuid
        drivers:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/Driver'

    Driver:
      title: Driver entity
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
          format: uuid
        date_created:
          type: string
          format: date-time
        username:
          type: string
        coordinate:
          $ref: '#/components/schemas/GeoLocation'
        online_status:
          $ref: '#/components/schemas/OnlineStatus'
        car:
          $ref: '#/components/schemas/Car'

    CreateDriver:
      title: Create new Driver entity
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 5
          maxLength: 64
        password:
          type: string
          description: |
            The password length must be greater than or equal to 8 |
            The password length must be less than 64 |
            The password must contain one or more uppercase characters |
            The password must contain one or more lowercase characters |
            The password must contain one or more numeric values |
            The password must contain one or more special characters
          pattern: '(?=^.{8,64}$)(?=.*\d)(?=.*[!@#$%^&*]+)(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$'

    OnlineStatus:
      title: Driver online status
      type: string
      enum:
        - ONLINE
        - OFFLINE

    GeoLocation:
      title: Geo coordinates of a Driver
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          format: double
          minimum: -90.
          maximum: 90.
        longitude:
          type: number
          format: double
          minimum: -180.
          maximum: 180.

    CountryCode:
      title: Codes for available countries
      enum:
        - US
        - DE
        - UK
      default: DE

    Engine:
      title: Car engine type
      type: string
      default: OIL
      enum:
        - OIL
        - ELECTRIC
        - GAS

    Manufacturer:
      title: Car manufacturer
      type: object
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
        date_created:
          type: string
          format: date-time
        name:
          type: string
        origin_country:
          $ref: '#/components/schemas/CountryCode'

    Car:
      title: Car entity
      required:
        - vin
        - manufacturer
        - model
        - license_plate
        - seat_count
        - engine_type
        - convertible
      type: object
      properties:
        id:
          type: string
          format: uuid
        date_created:
          type: string
          format: date-time
        vin:
          description: VIN number of car body
          type: string
          minLength: 6
          maxLength: 17
        manufacturer:
          $ref: '#/components/schemas/Manufacturer'
        model:
          type: string
        license_plate:
          type: string
          description: Licence plate installed on a car
          example: BMW555
        seat_count:
          type: integer
          format: int32
          default: 4
        engine_type:
          $ref: '#/components/schemas/Engine'
        convertible:
          type: boolean
          default: false
        rating:
          type: number
          format: float

    UpdateCar:
      title: Update Car parameters
      type: object
      properties:
        manufacturer:
          $ref: '#/components/schemas/Manufacturer'
        model:
          type: string
        license_plate:
          type: string
          description: Licence plate installed on a car
          example: BMW555
        seat_count:
          type: integer
          format: int32
        engine_type:
          $ref: '#/components/schemas/Engine'
        convertible:
          type: boolean
        rating:
          type: number
          format: float

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

